
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # Initialize the datasource with available DDL and DML scripts.
    platform: h2
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    #url: jdbc:p6spy:h2:mem:test
    url: jdbc:mysql://localhost:3306/coin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples: debug
server:
  port: 8088
# MyBatis-Plus 配置